---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Check spamassassin rsyslog config is present
      ansible.builtin.stat:
        path: /etc/rsyslog.d/spamassassin.conf
      register: rsyslog_conf
      failed_when: not rsyslog_conf.stat.exists

    - name: Check spamassassin log directory exists
      ansible.builtin.stat:
        path: /var/log/spamassassin
      register: log_dir
      failed_when: not log_dir.stat.exists
